name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Build and pack
      run: ldd --version


    #- name: Build and pack
      #run: sudo apt-get update -y && sudo apt-get upgrade && sh -c "$(curl -sSfL -o - https://compile.cuberite.org)"
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: cuberite
        path: |
         build-cuberite/Server/
             
      
